openapi: 3.0.0
info:
    title: "snowbee search"
    version: "1.0"
    description: "FOSS ecommerce search aggregator"
    contact:
        name: "Brod8362"
        url: "https://github.com/brod8362"

servers:
    - url: https://api.snowbee.byakuren.pw/
      description: "Primary server"
    - url: http://localhost:8080/
      description: "Local development server"

components:
  schemas:
    # Schema representing a specific vendor.
    # Will be returned by the API, represents which vendors are available to search
    Vendor:
        type: object
        properties:
            id:
                description: Vendor ID
                type: string
            name:
                description: Vendor name
                type: string
            url:
                description: Main site url
                type: string
            favicon:
                description: URL to site's favicon
                type: string
    # Schema representing an available filter.
    # Will be returned by the API, represents which filters are available to use
    Filter:
        type: object
        description: Filter description
        properties:
            id:
                description: Name of filter
                type: string
            name:
                description: Display name of the feilter (how it should be displayed to the user)
                type: string
            type:
                description: Type of the filter (e.g number, string)
                type: string
                oneOf:
                    - "str"
                    - "num"
                    - "range"
    # Represents a specific product returned by the API.
    Product:
        type: object
        description: Product schema
        properties:
            vendor_name:
                description: Name of the vendor
                type: string
            product_name:
                description: The name of the product
                type: string
            price:
                description: Price of the product
                type: number
            product_page_url:
                description: URL of the product page
                type: string
            properties:
                description: Array of properties
                type: object
    SearchQuery:
        type: object
        description: Schema for API input format
        properties:
            query:
                description: Search string
                type: string
            filters:
                description: List of filters
                type: array
    SearchResponse:
        type: object
        description: Schema for API response
        properties:
            products:
                description: List of products
                type: array
                items:
                    $ref: "#/components/schemas/Product"
    InfoResponse:
        type: object
        description: Response with information about the server and it's API version
        properties:
            version: 
                description: Version of the API
                type: string
            commit:
                description: Commit the server is running on
                type: string

paths:
    /search:
        post:
            description: Search for products
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SearchQuery"
            responses:
                200:
                    description: Search successful
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SearchResponse"
                404:
                    description: No results found

    /filters:
        get:
            description: Get the list of available filters
            responses:
                200:
                    description: Filters in response body
                    content:
                        application/json:
                            schema:
                                properties:
                                    filters:
                                        type: array
                                        items:
                                            $ref: "#/components/schemas/Filter"

    /vendors:
        get:
            description: Get the list of available vendors
            responses:
                200:
                    description: Vendors in response body
                    content:
                        application/json:
                            schema:
                                properties:
                                    vendors:
                                        type: array
                                        items:
                                            $ref: "#/components/schemas/Vendor"
    /info:
        get:
            description: Get info about the running API server
            responses:
                200:
                    description: Info in response body
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/InfoResponse"

